### PR TITLE
Feature: Handle spaces in path of a project.

### PR DESCRIPTION
**Pull request by Brett-Best**
This PR should fix running the following commands when the current path includes a directory with a space in it.

Commands fixed:
```bash
nef playground
nef build .
nef clean .
```

Commands not fixed:
```bash
nef jekyll
```

I was getting an error running `nef jekyll --project BowPlayground/ --output MD` even in a path that didn’t include spaces. The error: `error: render page page in playground BowPlayground, review '<project>/nef/docs/BowPlayground-page.log' for more information.` I had a look at the file referenced but I couldn’t find anything that could point me in the direction of what was wrong.

### CODE REVIEW

**Comment by Brett-Best** [comment]
Ideally would like to fix `nef jekyll` before merging this.

**Comment by miguelangel-dev** [comment]
@Brett-Best I really appreciate your improvements.

I have updated your branch:
- [x] Adding missed path protections for the rest of the variables.
- [x] Fixed Jekyll - It was a bug from Swift 5 migration, related to how we are getting the options from the command line for `nef-jekyll-page` script.
- [x] (bonus) Fixed template - remove unuseful `assets` folder for Playgrounds.

**Review by miguelangel-dev — APPROVED** [review]

**Comment by Brett-Best** [comment]
@miguelangel-dev cool, no worries 😄!

**Comment by miguelangel-dev** [comment]
@Brett-Best Released [`0.1.6`](https://github.com/bow-swift/nef/releases/tag/0.1.6) version with these changes! 

You can run `brew upgrade nef` to update to this version 🎉

PS: if you have any doubts about how `nef` is working or you want to discuss anything else you are welcome to join us to our Gitter's channel: https://gitter.im/bowswift/bow

**Pull request merged**
